apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-helper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homework-helper
  template:
    metadata:
      labels:
        app: homework-helper
    spec:
      containers:
        - name: homework-helper
          image: maxzabarka/homework-helper:latest
          ports:
            - containerPort: 3000
        - name: chat-app
          image: maxzabarka/runpod-chat:d529b176-677f-4a46-999f-779bb43c22c4
          ports:
            - containerPort: 80

